---
title: "Matrices"
author: "David Smz"
date: "10/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Matrices
```{r}
M = matrix(1:12, nrow = 4)
M
M2 = matrix(1:12, nrow = 4, byrow = TRUE)
M2
```

Contruir matrices a traves de filas o columnas o agregar filas o columnas a 
una matriz

```{r}
M
rbind(M, c(1,2,3), c(-1,-2,-3))
```

Matriz diagonal
```{r}
# a partir de un vector
diag(1:4)

# a partir de un numero con filas o columnas especificadas
diag(1, nrow = 4)
```

Posiciones de matriz y submatrices
```{r}
# elemento de una matriz
M[2,2]

# submatriz
M[c(1,3), 1:2]
```

Funciones de matrices
```{r}
notas = rbind(1:5, 6:10, 11:15, 16:20, 21:25)
notas

# diagonal de una matriz
diag(notas)

# numero de columnas y numero de filas
nrow(notas)
ncol(notas)

# suma de elementos y producto de elementos
sum(notas)
prod(notas)
```

```{r}
# suma de filas
rowSums(notas)

# suma de columnas
colSums(notas)

# media de columnas
colMeans(notas)
```

Aplicar una funcion a una matriz
```{r}
notas
apply(notas, MARGIN = 1, FUN = function(x){sqrt(sum(x^2))})
```

